### ISSUE TITLE
[Bug] File path error in component/demo/index.vue

### ISSUE THREAD

**Issue by hh2o4** [yanyu-fe/vite-plugin-vitepress-demo#2]
### 环境
wsl2
vscode

### 问题描述
如下图，在源码中, Expand组件的文件引入路径书写有误，导致`npm run dev:docs`报错，同时源码的错误导致v1.1.5的npm包中也有相同的问题。
![image](https://user-images.githubusercontent.com/20169617/167374857-d2c22382-dd2e-4872-80e1-5c51756bb1b0.png)

### 期望结果
修复文件引入路径，更新npm包，在使用该组件时不再出现报错。

**Comment by aibayanyu20** [comment]
建议先使用vuepress去做开发，对应的插件是地址[vuepress-code-block](https://github.com/yanyu-fe/vuepress-plugins/tree/main/plugins/code-block)，vitepress新版本的已经在开发中了
