### ISSUE TITLE
title 和 desc props是否可以设置为 required： false

### ISSUE THREAD

**Issue by HanSuhhi** [yanyu-fe/vite-plugin-vitepress-demo#5]
在我的项目当中，一些<demo /> 我并没有给desc和title属性，因为一些场景下我需要这样简洁的样式。

但是在开发环境下不填写desc和title会触发vue的warning，查看源码是因为以下代码导致的。
``` ts
const props = defineProps<{ src: string; title: string; desc: string }>()
```

虽然项目在打包后warning信息会被过滤掉，但在开发时面对控制台满满的黄色warning还是挺心烦的。

希望作者可以修改一下。

``` ts
const props = defineProps<{ src: string; title?: string; desc?: string }>()
```

**Comment by aibayanyu20** [comment]
升级到vite-plugin-vitepress-demo@2.0.0-alpha.8
