### ISSUE TITLE
代码块的样式丢失

### ISSUE THREAD

**Issue by hh2o4** [yanyu-fe/vite-plugin-vitepress-demo#6]
@aibayanyu20  作者你好，我在使用2.0.0-alpha.8插件的时候，发现代码块的样式和给出的例子不一致，查看引用的css文件，发现这里用到的这个变量值，在浏览器中显示没有定义。

请问这些变量值要依赖**其他特定版本的库**吗？还是说我的使用方式有问题呢？

![image](https://user-images.githubusercontent.com/20169617/226828477-ccb3603a-59cb-438a-98e5-e80f65678857.png)

![image](https://user-images.githubusercontent.com/20169617/226828731-979bb570-3105-4432-a10e-0f3cf0d0165d.png)

在npm包里全局搜索了一下变量值，也发现只有引用，而没有定义：

![image](https://user-images.githubusercontent.com/20169617/226829964-11e12d05-1952-4853-a75d-b61ca1c3649c.png)

代码块组件引入的地方如下图：

![image](https://user-images.githubusercontent.com/20169617/226828998-229c3588-23c1-4ed9-aaa3-ee95b8d84b89.png)

**Comment by aibayanyu20** [comment]
你目前使用的是哪个版本vitepress，可以提供一个复现demo吗？

**Comment by hh2o4** [comment]
> 你目前使用的是哪个版本vitepress，可以提供一个复现demo吗？

vitepress用的是0.22.3版本，demo现在有点大，我尝试下能不能新建一个小的复现。

**Comment by aibayanyu20** [comment]
目前插件支持vitepress@1.0.0-alpha.20以及以上版本，可以尝试升级到最新版本的试一下

**Comment by aibayanyu20** [comment]
[v1.0](https://github.com/yanyu-fe/vite-plugin-vitepress-demo/tree/v1.0)，低版本的可以参考v1.0的使用方式，目前已经不在维护1.x版本了。
